micronaut:
  application:
    name: api
datasources:
  default:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:codebrain-challenge}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:12345678}
    driverClassName: com.mysql.cj.jdbc.Driver
jackson:
  serializationInclusion: ALWAYS
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
flyway:
  datasources:
    default:
      enabled: true