CREATE TABLE `products`(
    `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL,
    `price` BIGINT UNSIGNED NOT NULL,
    `deleted` BIT(1) NOT NULL DEFAULT 0
);